CREATE SCHEMA IF NOT EXISTS globa_kutsenko;

CREATE TABLE IF NOT EXISTS globa_kutsenko.users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);